### ISSUE TITLE
Unable to see characters in textbox at password creation. 

### ISSUE THREAD

**Issue by iteachit** [WorldOfMogwais/WoM-Releases#1]
At first load, when it asks to create a password. We are **unable to see the characters** that we type in the text box. But it does capture what we type. 

![image](https://user-images.githubusercontent.com/40798317/75098549-92324200-5585-11ea-9749-bc4dabb42c34.png)

**Comment by darkfriend77** [comment]
thx, will check on this ...

**Comment by darkfriend77** [comment]
Implemented

https://github.com/WorldOfMogwais/WoM-Releases/releases/tag/0.26
