### ISSUE TITLE
Client stops on Block 1490

### ISSUE THREAD

**Issue by KryptoKev** [WorldOfMogwais/WoM-Releases#11]
My Game stops at Block 1490 if i use the "Fast" Button after an Adventure.
If i use the "Evolve" Button after the Adventure i can get past the block.

It is always happening on the same block.

**Comment by KryptoKev** [comment]
![image](https://user-images.githubusercontent.com/55624270/75470038-54238c80-5990-11ea-8c40-f3f939c358f3.png)

**Comment by darkfriend77** [comment]
https://github.com/WorldOfMogwais/WoM-Releases/releases/tag/v0.2.7.0
fixed.
