### ISSUE TITLE
Failed to revive

### ISSUE THREAD

**Issue by KryptoKev** [WorldOfMogwais/WoM-Releases#14]
My Mogwai is dead and if i want to revive him i just get the message "Failed to revive"

![image](https://user-images.githubusercontent.com/55624270/75605742-a924e700-5ae5-11ea-9600-bb48b8d1cc2c.png)

Also after the games has moved some blocks the Failure stays the same

**Comment by KryptoKev** [comment]
Also when i restart the Client i can't revive my Mogwai anymore

**Comment by KryptoKev** [comment]
With 0.27 i was able to revive my Mogwai again, was this bug solved or is it just temporary somehow ?

**Comment by KryptoKev** [comment]
Nope , after the first dead in 0.27 i can't revive my Mogwai anymore ...

**Comment by darkfriend77** [comment]
Do you have enough coins for revive? Check amount in bottom middle right next to the mogwais name. Is their a error message?

**Comment by KryptoKev** [comment]
Of course .... dammit , so a better Message would be good for de idiots like me ....
