### ISSUE TITLE
FFWD to next block event - Fast button

### ISSUE THREAD

**Issue by iteachit** [WorldOfMogwais/WoM-Releases#16]
![image](https://user-images.githubusercontent.com/40798317/75643830-2b102f80-5c0e-11ea-9308-4ab9ab31e147.png)

After pressing the fast button, its opacity drops and it becomes unavailable.  I understand that it Fast-Fowrards the user and stops at a block event.  When the event is an adventure, are we obligated to enter the adventure? 

Should we be able to click FAST again to go to the next event?

Regards,

**Comment by darkfriend77** [comment]
is this version 0.27?

**Comment by iteachit** [comment]
That was in Version 0.26.
We can close this issue.
