### ISSUE TITLE
Log is not readable

### ISSUE THREAD

**Issue by KryptoKev** [WorldOfMogwais/WoM-Releases#9]
The Logs during an adventure is not readable.
It looks like the logs are overlaying somehow.
![Meeseduplog](https://user-images.githubusercontent.com/55624270/75468817-28070c00-598e-11ea-82a6-9c12c6a11988.png)

**Comment by darkfriend77** [comment]
Also the log needs to be cleaned from the console color tags, for example [c:rDarkGray]
and better readability

**Comment by darkfriend77** [comment]
https://github.com/WorldOfMogwais/WoM-Releases/releases/tag/v0.2.7.0
fixed and improved
